### PR TITLE
split up section on pub standards and sorting

### PR DESCRIPTION
**Pull request by tilfischer**

### CODE REVIEW

**Comment by jliermann** [comment]
@tilfischer Renaming files leads to issues with the localisation. Can the same order also be achieved with renaming less files?

**Comment by tilfischer** [comment]
Good point! I will have a look!

**Comment by jliermann** [comment]
@nap84 The split is fine, I also like getting rid of "monster" pages. I was just refering to the renamed (but unchanged) documents which will cause problems.

**Comment by tilfischer** [comment]
...as this will require us to provide the translation again. I totally forgot about this. Thanks for pointing this out. Actually we just need to get rid of [f2c7124](https://github.com/NFDI4Chem/knowledge_base/pull/382/commits/f2c71242e18dbfe8096a94e5806a26594a1fa7b5) and [6d4b839](https://github.com/NFDI4Chem/knowledge_base/pull/382/commits/6d4b839f51817c7c787429903292c6eefa297a66). I am fine with cherry picking. ;)

**Pull request merged**
